version: 2
jobs:
  build-job:
    docker:
      - image: circleci/python:3.6.1
        environment:
          CONFIG_NAME: testing
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: circleci_test_password
          POSTGRES_USER: ubuntu
    steps:
      - checkout
      - restore_cache:
          keys:
          # fallback to using the latest cache if no exact match is found
          - deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          - deps1-{{ .Branch }}-
      - run:
          name: Install requirements.txt
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: Install AWS CLI
          command: |
            . venv/bin/activate
            pip install awscli
            aws --version
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Download Environment Variables
          command: |
            . venv/bin/activate
            aws s3 cp s3://albatross.api.config/test_environment_variables.sh ./environment_variables.sh
      - run:
          command: |
            . venv/bin/activate
            source ./environment_variables.sh
            export DB_HOST="127.0.0.1"
            export DB_NAME="circle_test"
            export DB_PASSWORD="circleci_test_password"
            export DB_PORT=5432
            export DB_USER="ubuntu"
            cd b3i
            python ./manage.py test
            python ./manage.py behave

  deploy-job:
    machine: true
    steps:
      - run: ssh -p 50005 -i /home/ubuntu/.ssh/id_production deploy@34.195.47.179 "/var/www/albatross_api/atomic_deployments.sh"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master